//Casos de uso específicos

export * from './educational-institution/create-educational-institution.use-case';
export * from './educational-institution/delete-educational-institution.use-cases';
export * from './educational-institution/get-educational-institution-by-id.use-case';
export * from './educational-institution/get-all-educational-institution.use-case';
export * from './educational-institution/update-educational-institution.use-case';
export * from '../use-cases/major/create-major.use-case';
export * from '../use-cases/major/get-all-majors.use-case';
export * from '../use-cases/major/get-major-by-id.use-case';
export * from '../use-cases/major/update-major.use-case';
export * from '../use-cases/major/delete-major.use-case';
export * from '../use-cases/user/create-user.use-case';
export * from '../use-cases/user/delete-user.use-case';
export * from '../use-cases/user/get-all-users.use-case';
export * from '../use-cases/user/get-user-by-id.use-case';
export * from '../use-cases/user/update-user.use-case';
export * from '../use-cases/comment/create-comment.use-case';
export * from './comment/get-all-comments.use-case';
export * from '../use-cases/comment/get-comment-by-id.use-case';
export * from '../use-cases/comment/update-comment.use-case';
export * from '../use-cases/comment/delete-comment.use-case';